#Text-Preprocessing

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv('/content/drive/Othercomputers/My PC/Documents/Drive/DeepLearning/NLP/train.txt', sep = ';', header=None, names = ['text','emotions'])

In [8]:
df.head()

                                                text emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [9]:
df.isnull().sum()

text        0
emotions    0
dtype: int64

In [14]:
unique_emotions = df['emotions'].unique()
emotion_numbers = {}
i=0

for em in unique_emotions:
  emotion_numbers[em]= i
  i+=1
df['emotions'] = df['emotions'].map(emotion_numbers)

In [15]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

#To lowerCase

In [16]:
df['text'] = df['text'].apply( lambda x : x.lower())

#Remove Punctuations

In [18]:
import string

def remove_punctuations(text):
  return text.translate(str.maketrans('','',string.punctuation))

In [19]:
df['text'] = df['text'].apply(remove_punctuations)

#Remove Numbers

In [21]:
import re

def remove_numbers(text):
  return re.sub(r'\d+', '', text)

df['text'] = df['text'].apply(remove_numbers)

#Remove URLS/LINKS

In [23]:
import re

def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

df['text'] = df['text'].apply(remove_urls)

# Remove Emojis and Special Chracters

In [25]:
def remove_emojis_and_special_chars(text):
    # Keep only alphanumeric characters and spaces
    return ''.join(char for char in text if char.isalnum() or char.isspace())

df['text'] = df['text'].apply(remove_emojis_and_special_chars)

# Removing Stopwords

In [26]:
import nltk

In [27]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [28]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [33]:
stop_words = set(stopwords.words('english'))

In [36]:
def remove_stopwords(text):
    words = word_tokenize(text)
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return ' '.join(filtered_words)

In [39]:
nltk.download('punkt_tab', quiet=True)
df['text'] = df['text'].apply(remove_stopwords)

In [40]:
df['text']

0                                    didnt feel humiliated
1        go feeling hopeless damned hopeful around some...
2                im grabbing minute post feel greedy wrong
3        ever feeling nostalgic fireplace know still pr...
4                                          feeling grouchy
                               ...
15995        brief time beanbag said anna feel like beaten
15996    turning feel pathetic still waiting tables sub...
15997                             feel strong good overall
15998                       feel like rude comment im glad
15999                         know lot feel stupid portray
Name: text, Length: 16000, dtype: object